'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace NTi.Modules.DFT_EDI_CheckingF04_Manual

    '''<summary>
    '''ViewDFT_EDI_CheckingF04_Manual class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class ViewDFT_EDI_CheckingF04_Manual

        '''<summary>
        '''RadAjaxManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblReturnMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReturnMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cboSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSite As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''rdpFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpFromDate As Global.Telerik.Web.UI.RadDatePicker

        '''<summary>
        '''rdpToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpToDate As Global.Telerik.Web.UI.RadDatePicker

        '''<summary>
        '''dropFormType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dropFormType As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rgCertificateList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgCertificateList As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''lblRoleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRoleID As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
