'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3662
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Invoice class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class Invoice

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''dlInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlInvoice As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblSumNetWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumNetWeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumNetWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumNetWeightUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumGrossWeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumGrossWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumGrossWeightUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity1Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity1Unit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity2Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity2Unit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity3Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity3Unit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity4Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity4Unit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumQuantity5Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumQuantity5Unit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumFOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumCIF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumCIF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumCFR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumCFR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hSumPackagePerInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSumPackagePerInvoice As Global.System.Web.UI.WebControls.HiddenField
End Class
