'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace NTi.Modules.DFT_EDI_CancelInvoice

    '''<summary>
    '''ViewDFT_EDI_CancelInvoice class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class ViewDFT_EDI_CancelInvoice

        '''<summary>
        '''RadAjaxManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''RadCodeBlockFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlockFirst As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''RadWindowManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

        '''<summary>
        '''SearchDialog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchDialog As Global.Telerik.Web.UI.RadWindow

        '''<summary>
        '''DeleteDialog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeleteDialog As Global.Telerik.Web.UI.RadWindow

        '''<summary>
        '''RadCodeBlock2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''txtCompanyName_Eng control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompanyName_Eng As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''btnSelectCompany control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSelectCompany As Global.BeanSoftware.ShortcutButton

        '''<summary>
        '''txtCompany_Taxno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_Taxno As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''btnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClear As Global.BeanSoftware.ShortcutButton

        '''<summary>
        '''txtInvoiceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInvoiceNo As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.BeanSoftware.ShortcutButton

        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rblSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''btnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDelete As Global.BeanSoftware.ShortcutButton

        '''<summary>
        '''rgInvoiceList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgInvoiceList As Global.Telerik.Web.UI.RadGrid
    End Class
End Namespace
