'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ctrlFORM1 class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ctrlFORM1

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadCodeBlockFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockFirst As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''ViewDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDialog As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''txtInvHRunAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvHRunAuto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRequestPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestPerson As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompanyTaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyTaxNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFormNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompanyProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyProvince As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompanyCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompanyPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompanyFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyFax As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCardID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardID As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''dropDestRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDestRemark As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtOB_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOB_Address As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAuthorize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuthorize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtComapnyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComapnyEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''txtDestinationCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationCompany As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationTaxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationTaxID As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationProvince As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestReceiveCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestReceiveCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''dropDestinationCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDestinationCountry As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''dropDestRemark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDestRemark1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtOB_Dest_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOB_Dest_Address As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationFax As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDestinationEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock3 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''radShipBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radShipBy As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtTransportBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportBy As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock4 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''grdItemData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdItemData As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''txtGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrossWeight As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpG_UNIT_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpG_UNIT_CODE As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''dropWeightDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropWeightDisplay As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtQuantity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity1 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpQ_UNIT_CODE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpQ_UNIT_CODE1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtQuantity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity2 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpQ_UNIT_CODE2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpQ_UNIT_CODE2 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtQuantity3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity3 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpQ_UNIT_CODE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpQ_UNIT_CODE3 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtQuantity4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity4 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpQ_UNIT_CODE4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpQ_UNIT_CODE4 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtQuantity5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity5 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''drpQ_UNIT_CODE5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpQ_UNIT_CODE5 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadCodeBlock5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock5 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''txtInvoiceNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtInvoiceDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate1 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtInvoiceNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtInvoiceDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate2 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtInvoiceNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtInvoiceDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate3 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtInvoiceNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo4 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtInvoiceDate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate4 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtInvoiceNo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo5 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtInvoiceDate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate5 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''radBillType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBillType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtBillTypeOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillTypeOther As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBlNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSailingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSailingDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtEdiDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEdiDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadCodeBlock6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock6 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''txtAttachFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttachFile As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock7 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''txtFactory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactory As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryTaxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryTaxID As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryProvince As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFactoryFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactoryFax As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SqlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCountry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Sqlunit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqlunit As Global.System.Web.UI.WebControls.SqlDataSource
End Class
