'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NTi.Modules.DFT_EDI2B_Report_01
    
    Partial Public Class ViewDFT_EDI2B_Report_01
        
        '''<summary>
        '''RadAjaxManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
        
        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
        
        '''<summary>
        '''rdpFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpFromDate As Global.Telerik.Web.UI.RadDatePicker
        
        '''<summary>
        '''rdpToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdpToDate As Global.Telerik.Web.UI.RadDatePicker
        
        '''<summary>
        '''ddlSiteID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSiteID As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''grdData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdData As Global.Telerik.Web.UI.RadGrid
        
        '''<summary>
        '''lblRoleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRoleID As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
