'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace NTi.Modules.DFT_EDI_BookingForm

    '''<summary>
    '''ViewDFT_EDI_BookingForm class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class ViewDFT_EDI_BookingForm

        '''<summary>
        '''RadAjaxManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''tdCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdCard As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''tblCardDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCardDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''RadTabStrip1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''RadPageView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock3 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''txtCompanyName_Eng control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompanyName_Eng As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCompany_Taxno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_Taxno As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCompany_BranchNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_BranchNo As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCompany_Address control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_Address As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCompany_Phone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_Phone As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCompany_Fax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompany_Fax As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize1 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize2 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize3 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize4 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize5 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthorize6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthorize6 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtAuthName_Eng control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthName_Eng As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtCardLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCardLevel As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtReturnMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReturnMsg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tblBlackList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblBlackList As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''RadCodeBlock7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock7 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblBlackList_Msg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBlackList_Msg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdBlackListTab1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdBlackListTab1 As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''tblRefList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRefList As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''RadCodeBlock6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock6 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''txtFormNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFormNum As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rcbFormType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbFormType As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnInsertItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnInsertItem As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumber As Global.Telerik.Web.UI.RadNumericTextBox

        '''<summary>
        '''btnPrintBarcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrintBarcode As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''rgRequestForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgRequestForm As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''RadPageView2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''rgCardList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgCardList As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''RadPageView3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock4 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''rgDocAttach control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgDocAttach As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''RadPageView4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock5 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''rgBackList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgBackList As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''txtCard_Id control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCard_Id As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRoleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRoleID As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
